config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :cart, controller: 'cart', only: %i[show update edit] do
    member do
      post :add_product
      post :remove_product
      get  :confirmation
      post :finish
    end
  end

  namespace :admin do
    get 'orders/index'
    get 'orders/show'
    root to: 'products#index'
    resources :products
    resources :categories
    resources :orders, only: %i[show index update]
  end

  get 'regulamin', to: 'static#terms', as: :terms
  get 'polityka-prywatnosci', to: 'static#privacy', as: :privacy
  get 'dostawa', to: 'static#shipping', as: :shipping
  get 'o-sklepie', to: 'static#about', as: :about

  root to: 'products#index'
  resources :products, only: %i[show index], path: 'produkt'
  resources :categories, only: [:show], path: 'kategoria'
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :order

  validates :first_name, :last_name, :zip_code, :street, :email, :city, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true

  def to_param
    "#{id}-#{name}".parameterize
  end
end

app/models/line_item.rb
# frozen_string_literal: true

class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  def full_price
    unit_price * quantity
  end
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  include Statesman::Adapters::ActiveRecordQueries[
    transition_class: OrderTransition,
    initial_state: :new
  ]
  belongs_to :shipping_type, optional: true
  has_many :line_items
  has_one :address
  has_many :transitions, class_name: 'OrderTransition', autosave: false

  accepts_nested_attributes_for :address, update_only: true

  delegate :can_transition_to?,
           :current_state, :history, :last_transition, :last_transition_to,
           :transition_to!, :transition_to, :in_state?, to: :state_machine

  def state_machine
    @state_machine ||= OrderStateMachine.new(self, transition_class: OrderTransition, association_name: :transitions)
  end

  def full_cost
    line_items.map(&:full_price).sum + shipping_cost
  end

  def self.transition_class
    OrderTransition
  end

  def self.initial_state
    OrderStateMachine.initial_state
  end

  def self.transition_name
    :transitions
  end
end

app/models/order_state_machine.rb
# frozen_string_literal: true

class OrderStateMachine
  include Statesman::Machine

  state :new, initial: true
  state :confirmed
  state :in_progress
  state :shipped
  state :cancelled

  transition from: :new, to: %i[confirmed cancelled]
  transition from: :confirmed, to: %i[in_progress cancelled]
  transition from: :in_progress, to: %i[shipped cancelled]
  transition from: :shipped, to: [:cancelled]

  after_transition(to: :cancelled) do |order, _transition|
    OrderMailer.order_cancelled(order).deliver
  end

  after_transition(to: :confirmed) do |order, _transition|
    OrderMailer.order_confirmation(order).deliver
  end

  after_transition(to: :in_progress) do |order, _transition|
    OrderMailer.order_in_progress(order).deliver
  end

  after_transition(to: :shipped) do |order, _transition|
    OrderMailer.order_shipped(order).deliver
  end

  def self.states_map
    {
      'new' => 'Niepotwierdzone',
      'confirmed' => 'Złożone przez klienta',
      'in_progress' => 'Przyjęte do realizacji',
      'shipped' => 'Wysłane',
      'cancelled' => 'Anulowane'
    }
  end
end

app/models/order_transition.rb
# frozen_string_literal: true

class OrderTransition < ApplicationRecord
  include Statesman::Adapters::ActiveRecordTransition

  # If your transition table doesn't have the default `updated_at` timestamp column,
  # you'll need to configure the `updated_timestamp_column` option, setting it to
  # another column name (e.g. `:updated_on`) or `nil`.
  #
  # self.updated_timestamp_column = :updated_on
  # self.updated_timestamp_column = nil

  belongs_to :order, inverse_of: :transitions

  # after_destroy :update_most_recent, if: :most_recent?

  # private

  # def update_most_recent
  #   last_transition = order.order_transitions.order(:sort_key).last
  #   return unless last_transition.present?
  #   last_transition.update_column(:most_recent, true)
  # end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :category

  validates :name, presence: true
  validates :description, presence: true
  validates :price, numericality: { greater_than: 0.0 }
  validates :category, presence: true

  mount_uploader :photo, ProductPhotoUploader
  # serialize :photo, JSON

  def to_param
    "#{id}-#{name}".parameterize
  end
end

app/models/shipping_type.rb
# frozen_string_literal: true

class ShippingType < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_cart

  def current_cart
    if session[:order_id]
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

  def current_cart_or_create
    c = current_cart
    if c.new_record?
      c.save
      session[:order_id] = c.id
    end
    c
  end
end

app/controllers/cart_controller.rb
# frozen_string_literal: true

class CartController < ApplicationController
  def show
    @cart = current_cart
  end

  def edit
    @cart = current_cart
    @cart.build_address if @cart.address.blank?
  end

  def update
    @cart = current_cart
    if @cart.update(cart_attributes)
      @cart.update_attribute(:shipping_cost, @cart.shipping_type.cost)
      redirect_to confirmation_cart_path
    else
      render action: :edit
    end
  end

  def confirmation
    @cart = current_cart
  end

  def finish
    @cart = current_cart
    @cart.transition_to :confirmed
    session.delete(:order_id)
    flash[:notice] = 'Dziękujemy za zamówienie!'
    redirect_to root_path
  end

  def add_product
    order = current_cart_or_create
    product = Product.find(params[:product_id])
    if item = order.line_items.where(product:).first
      item.quantity += 1
      item.save
    else
      order.line_items.create product:,
                              quantity: 1,
                              unit_price: product.price,
                              item_name: product.name
    end
    redirect_back(fallback_location: root_path, notice: 'Dodano produkt do koszyka')
  end

  def remove_product
    order = current_cart

    product = Product.find(params[:product_id])
    item = order.line_items.where(product:).first
    item&.destroy
    redirect_back(fallback_location: root_path, notice: 'Usunięto produkt z koszyka')
  end

  private

  def cart_attributes
    params.require(:order).permit(
      :shipping_type_id,
      :comment,
      address_attributes: %i[
        first_name
        last_name
        city
        zip_code
        street
        email
      ]
    )
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @products = @category.products.page(params[:page]).per(6)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.order(created_at: :desc).limit(9)
  end

  def show
    @product = Product.find(params[:id])
    @category = @product.category
  end
end

app/controllers/static_controller.rb
# frozen_string_literal: true

class StaticController < ApplicationController
  def terms; end

  def privacy; end

  def shipping; end

  def about; end
end

app/helpers/admin/base_helper.rb
# frozen_string_literal: true

module Admin
  module BaseHelper
  end
end

app/helpers/admin/categories_helper.rb
# frozen_string_literal: true

module Admin
  module CategoriesHelper
  end
end

app/helpers/admin/products_helper.rb
# frozen_string_literal: true

module Admin
  module ProductsHelper
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/static_helper.rb
# frozen_string_literal: true

module StaticHelper
end

app/views/cart/confirmation.html.erb
<h1>Potwierdź zamówienie</h1>

<table class="table table-striped">
  <thead>
    <th>Produkt</th>
    <th>Liczba sztuk</th>
    <th>Cena jednostkowa</th>
    <th>Cena całkowita</th>
  </thead>
  <tbody>
    <% @cart.line_items.each do |line_item| %>
      <tr>
        <td><%= link_to line_item.item_name, product_path(line_item.product) %>
        <td><%= line_item.quantity %></td>
        <td><%= number_to_currency line_item.unit_price %></td>
        <td><%= number_to_currency line_item.full_price %></td>
      </tr>
    <% end %>
    <tr>
      <td>Dostawa: <%= @cart.shipping_type.name %></td>
      <td></td>
      <td colspan="2"><%= number_to_currency @cart.shipping_cost %></td>
    </tr>
    <tr>
      <td colspan="4"><hr/></td>
    </tr>
    <tr>
      <th>Całość</th>
      <td></td>
      <td colspan="2"><%= number_to_currency @cart.full_cost %></td>
    </tr>
  </tbody>
</table>

<%= link_to finish_cart_path, method: :post, class: "btn btn-success btn-lg" do %>
  <span class="fa fa-check"></span>
  Potwierdzam zamówienie z obowiązkiem zapłaty
<% end %>

app/views/cart/edit.html.erb
<h1>Dostawa</h1>

<div class="row">
  <div class="col-md-6">
    <%= simple_form_for @cart, url: cart_path do |f| %>
      <%= f.simple_fields_for :address do |a| %>
        <%= a.input :email %>
        <%= a.input :first_name %>
        <%= a.input :last_name %>
        <%= a.input :city %>
        <%= a.input :zip_code %>
        <%= a.input :street %>
      <% end %>
      <%= f.association :shipping_type, as: :select, prompt: nil %>
      <%= f.input :comment %>
      <%= button_tag class: "btn btn-success btn-lg" do %>
        Zapisz i przejdź dalej
        <span class="fa fa-step-forward"></span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/cart/show.html.erb
<h1>Twój koszyk</h1>
<% if @cart.line_items.empty? %>
  <p>Twój koszyk jest pusty!</p>
<% else %>
  <table class="table table-striped">
    <thead>
      <th>Produkt</th>
      <th>Liczba sztuk</th>
      <th>Cena jednostkowa</th>
      <th>Cena całkowita</th>
      <th></th>
    </thead>
    <tbody>
      <% @cart.line_items.each do |line_item| %>
        <tr>
          <td><%= link_to line_item.item_name, product_path(line_item.product) %>
          <td><%= line_item.quantity %></td>
          <td><%= number_to_currency line_item.unit_price %></td>
          <td><%= number_to_currency line_item.full_price %></td>
          <td>
            <%= link_to "Usuń", remove_product_cart_path(product_id: line_item.product.id), method: :post, class:"btn btn-danger btn-xs" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <p>
    <%= link_to edit_cart_path, class: "btn btn-success btn-lg" do %>
      Przejdź dalej
      <span class="fa fa-step-forward"></span>
    <% end %>
  </p>
<% end %>