config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :cart, controller: 'cart', only: %i[show update edit] do
    member do
      post :add_product
      post :remove_product
      get  :confirmation
      post :finish
    end
  end

  namespace :admin do
    get 'orders/index'
    get 'orders/show'
    root to: 'products#index'
    resources :products
    resources :categories
    resources :orders, only: %i[show index update]
  end

  get 'regulamin', to: 'static#terms', as: :terms
  get 'polityka-prywatnosci', to: 'static#privacy', as: :privacy
  get 'dostawa', to: 'static#shipping', as: :shipping
  get 'o-sklepie', to: 'static#about', as: :about

  root to: 'products#index'
  resources :products, only: %i[show index], path: 'produkt'
  resources :categories, only: [:show], path: 'kategoria'
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :category

  validates :name, presence: true
  validates :description, presence: true
  validates :price, numericality: { greater_than: 0.0 }
  validates :category, presence: true

  mount_uploader :photo, ProductPhotoUploader
  # serialize :photo, JSON

  def to_param
    "#{id}-#{name}".parameterize
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

module Admin
  class ProductsController < Admin::BaseController
    def index
      @q = Product.ransack(params[:q])
      @products = @q.result(distinct: true).page(params[:page]).per(30)
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
      if @product.save
        redirect_to admin_products_path, notice: 'Pomyślnie dodano produkt.'
      else
        render action: :new
      end
    end

    def edit
      @product = Product.find(params[:id])
    end

    def update
      @product = Product.find(params[:id])
      if @product.update_attributes(product_params)
        redirect_to admin_products_path, notice: 'Pomyślnie usunięto produkt'
      else
        render action: :edit
      end
    end

    private

    def product_params
      params.require(:product).permit(
        :name,
        :category_id,
        :description,
        :long_description,
        :price,
        :photo
      )
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.order(created_at: :desc).limit(9)
  end

  def show
    @product = Product.find(params[:id])
    @category = @product.category
  end
end

app/helpers/admin/products_helper.rb
# frozen_string_literal: true

module Admin
  module ProductsHelper
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin, @product] do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :long_description %>
  <%= f.input :price %>
  <%= f.association :category %>
  <%= f.input :photo %>
  <%= f.submit %>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Edycja produktu</h1>

<%= render partial: "form" %>

app/views/admin/products/index.html.erb
<h1>Produkty</h1>

<%= link_to new_admin_product_path, class: "btn btn-success" do %>
  <span class="fa fa-plus"></span> Dodaj nowy produkt
<% end %>

<div class="search-form">
  <%= search_form_for [:admin, @q] do |f| %>
    <%= f.text_field :name_or_description_or_long_description_cont, placeholder: "Szukaj tekstu" %>
    <%= f.text_field :price_gt, placeholder: "Cena >" %>
    <%= f.submit "Szukaj" %>
  <% end %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sort_link(@q, :name, "Nazwa") %></th>
      <th><%= sort_link(@q, :price, "Cena") %></th>
      <th>Kategoria</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= number_to_currency product.price %></td>
        <td><%= product.category.name %></td>
        <td>
          <%= link_to "Edycja", edit_admin_product_path(product), class: "btn btn-default btn-xs" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @products %>

app/views/admin/products/new.html.erb
<h1>Dodawanie produktu</h1>

<%= render partial: "form" %>