config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :cart, controller: 'cart', only: %i[show update edit] do
    member do
      post :add_product
      post :remove_product
      get  :confirmation
      post :finish
    end
  end

  namespace :admin do
    get 'orders/index'
    get 'orders/show'
    root to: 'products#index'
    resources :products
    resources :categories
    resources :orders, only: %i[show index update]
  end

  get 'regulamin', to: 'static#terms', as: :terms
  get 'polityka-prywatnosci', to: 'static#privacy', as: :privacy
  get 'dostawa', to: 'static#shipping', as: :shipping
  get 'o-sklepie', to: 'static#about', as: :about

  root to: 'products#index'
  resources :products, only: %i[show index], path: 'produkt'
  resources :categories, only: [:show], path: 'kategoria'
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :category

  validates :name, presence: true
  validates :description, presence: true
  validates :price, numericality: { greater_than: 0.0 }
  validates :category, presence: true

  mount_uploader :photo, ProductPhotoUploader
  # serialize :photo, JSON

  def to_param
    "#{id}-#{name}".parameterize
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

module Admin
  class ProductsController < Admin::BaseController
    def index
      @q = Product.ransack(params[:q])
      @products = @q.result(distinct: true).page(params[:page]).per(30)
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
      if @product.save
        redirect_to admin_products_path, notice: 'Pomyślnie dodano produkt.'
      else
        render action: :new
      end
    end

    def edit
      @product = Product.find(params[:id])
    end

    def update
      @product = Product.find(params[:id])
      if @product.update_attributes(product_params)
        redirect_to admin_products_path, notice: 'Pomyślnie usunięto produkt'
      else
        render action: :edit
      end
    end

    private

    def product_params
      params.require(:product).permit(
        :name,
        :category_id,
        :description,
        :long_description,
        :price,
        :photo
      )
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.order(created_at: :desc).limit(9)
  end

  def show
    @product = Product.find(params[:id])
    @category = @product.category
  end
end

app/helpers/admin/products_helper.rb
# frozen_string_literal: true

module Admin
  module ProductsHelper
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/_products.html.erb
<% products.each_slice(3) do |slice| %>
  <div class="row">
    <% slice.each do |product| %>
      <div class="col-md-4">
        <div class="thumbnail">
          <%= link_to product_path(product) do %>
            <%= image_tag Faker::Placeholdit.image("640x480", 'jpg', 'cccccc') %>
          <% end %>
          <div class="caption">
            <h3><%= link_to product.name, product %></h3>
            <p><%= simple_format(truncate(product.description, length: 90)) %></p>
            <p class="lead"><%= number_to_currency product.price %></p>
            <p>
              <%= link_to add_product_cart_path(product_id: product.id), method: :post, class: "btn btn-primary" do %>
                <span class="fa fa-shopping-cart"> Dodaj do koszyka
              <% end %>
            </p>
          </div>
          </div> 
        </div>
    <% end %>
  </div>
<% end %>

app/views/products/index.html.erb
<h1>Najnowsze produkty</h1>

<%= render partial: 'products', locals: { products: @products } %>

app/views/products/show.html.erb
<div class="container-fluid">
  <div class="col-md-5">
    <h1><%= @product.name %></h1>
    <p class="lead"><%= @product.description %></p>
    <%= simple_format(@product.long_description) %>

    <p class="lead"><%= number_to_currency(@product.price) %></p>
    <p>
      <%= link_to add_product_cart_path(product_id: @product.id), method: :post, class: "btn btn-primary" do %>
        <span class="fa fa-shopping-cart"> Dodaj do koszyka
      <% end %>
    </p>
  </div>
  <div class="col-md-7">
    <%= image_tag Faker::Placeholdit.image("640x480", 'jpg', 'cccccc'), class: "img-responsive" %>
  </div>
</div>